IIN2_DREAMS/urls.py
# project_name/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static # Import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),  # Include employee app's URLs
]

# Add static/media URL configurations if needed
# ...

# Don't forget to import settings and static if you're handling media files in development.


# ... (other URL patterns)

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
# employee/urls.py
from django.urls import path
from . import views

app_name = 'employees'  # Namespace for the app

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('Loginpage/', views.Loginpage, name='Loginpage'),
    path('logoutpage/', views.logoutpage, name='logoutpage'),
    path('check_in', views.check_in, name='check_in'),
    
    # Add other paths as needed
]

employees/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Employees(models.Model):
    user=models.OneToOneField(User,blank=True,null=True,on_delete=models.CASCADE,related_name='employees')
    empname=models.CharField(max_length=100,null=True)
    email=models.EmailField(max_length=100)
    number=models.CharField(max_length=10,null=True)
    password=models.CharField(max_length=100)
    profile_pic=models.ImageField(default="pic.png",null=True,blank=True)
    def __str__(self):
        return self.empname
    
class Check_in(models.Model):
    check_in_time = models.DateTimeField(auto_now_add=True)
    ip_address = models.CharField(max_length=100)

class TimeSheet(models.Model):
    empname = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    ip_address = models.CharField(max_length=50)
    day = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return f"{self.emp_name} - {self.day} {self.time}"
    

employees/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm


class CreateEmpForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class CheckInForm(forms.Form):
    empname = forms.CharField(max_length=100)
    place = forms.CharField(max_length=100)
    # You can customize this form based on your requirements

employees/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .forms import *
from django.http import JsonResponse
from .forms import CheckInForm
from .models import TimeSheet
from django.http import HttpResponseRedirect
import datetime

from django.http import HttpResponse
from .tasks import *
from django.shortcuts import render
import time
import schedule
from django.utils import timezone



from django.http import HttpResponse

import json

# Create your views here.


def index(request):
    
    return render(request,'index.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        form = CreateEmpForm()
        if request.method == 'POST':
            form = CreateEmpForm(request.POST)
            if form.is_valid():
                user = form.save()  
                username = form.cleaned_data.get('username')
                
                
                group = Group.objects.get(name='employee')
                user.groups.add(group)
                
               
                Employees.objects.create(user=user, empname=user.username, email=user.email)
                
                messages.success(request, 'User successfully created for ' + username)
                return redirect('register')  

        context = {'form': form}
        return render(request, 'register.html', context)


def Loginpage(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user =authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('/') 
        else:
            messages.info(request,'empname or password error')
            print("employee_name or password error ")
            return redirect('Loginpage')
    return render(request,'login.html')

def logoutpage(request):
    logout(request)
    return redirect('/')



def check_in(request):
    if request.method == 'POST':
       
        ip_address = request.META.get('REMOTE_ADDR')

        
        check_in_instance = Check_in.objects.create(ip_address=ip_address)
        check_in_instance.save()

        return HttpResponse("Checked in successfully!")
    else:
        return HttpResponse("Invalid request method.")

templates/check_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'check_in' %}" method="post">
        {% csrf_token %}
        <button type="submit">Check In</button>
    </form>
</body>
</html>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>IIN2 DREAMS</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- themify CSS -->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="#">
                            <h3>IIN2 DREAMS</h3>
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                {% if user.is_authenticated %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="about.html">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="blog.html">Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">Contact</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="logoutpage">Logout</a>
                                </li>
                                {% else %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="about.html">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="blog.html">Blog</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="register" id="navbarDropdown"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Register/Login
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="register">Register</a>
                                        <a class="dropdown-item" href="Loginpage">Login</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">Contact</a>
                                </li>
                                
                                
                                {% endif %}
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-xl-6">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h3>
                                {% if user.is_authenticated %}
                                Welcome {{request.user}}
                                {% endif %}
                            </h3>
                            <h1>Welcome to
                                IIN2 DREAMS</h1>
                            {% if user.is_authenticated %}
                            <!-- <button id="checkInBtn">Check In</button> -->
                            <!-- Your HTML template -->
                            <form method="post" action="check_in">
                             {% csrf_token %}
                             <input type="submit" value="Check In">
                            </form>


                            <!-- <a href="check_in" id="checkInBtn" class="btn_1">Check In</a> -->
                            <a href="#" class="btn_2">Check Out</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- footer part start-->
    <footer class="footer-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-md-4 col-xl-3">
                    <div class="single-footer-widget footer_1">
                        <a href="index"> <img src="img/logo.png" alt=""> </a>
                        <p>But when shot real her. Chamber her one visite removal six
                            sending himself boys scot exquisite existend an </p>
                        <p>But when shot real her hamber her </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Newsletter</h4>
                        <p>Stay updated with our latest trends Seed heaven so said place winged over given forth fruit.
                        </p>
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Enter email address'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email address'">
                                    <div class="input-group-append">
                                        <button class="btn btn_1" type="button"><i class="ti-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="social_icon">
                            <a href="#"> <i class="ti-facebook"></i> </a>
                            <a href="#"> <i class="ti-twitter-alt"></i> </a>
                            <a href="#"> <i class="ti-instagram"></i> </a>
                            <a href="#"> <i class="ti-skype"></i> </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-md-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Contact us</h4>
                        <div class="contact_info">
                            <p><span> Address :</span> Hath of it fly signs bear be one blessed after </p>
                            <p><span> Phone :</span> +2 36 265 (8060)</p>
                            <p><span> Email : </span>info@colorlib.com </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        
    </footer>
    <!-- footer part end-->

    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>
<script>
    document.addEventListener('DOMContentLoaded', function () {
      const checkInBtn = document.getElementById('checkInBtn');

      checkInBtn.addEventListener('click', function () {
        // Perform an asynchronous request to handle the check-in
        fetch("{% url 'employees:check_in' %}", {
          method: 'POST',
          headers: {
            'X-CSRFToken': "{{ csrf_token }}",
          },
        })
        .then(response => response.json())
        .then(data => {
          // Update the UI based on the response
          if (data.success) {
            checkInBtn.parentNode.innerHTML = "<p>You have successfully checked in.</p>";
          } else {
            console.error("Check-in failed");
          }
        })
        .catch(error => console.error("Error during check-in:", error));
      });
    });
  </script>
</html>

templates/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>IIN2 DREAMS</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- themify CSS -->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index">
                            <h3>IIN2 DREAMS</h3>
                        </a>
                        
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- banner part start-->
    <div class="container">
        <div class="row">
          <div class="main">
            <h3>Login</h3>
            <form role="form" method="POST" action="">
                {% csrf_token %}
              <div class="form-group">
                <label for="inputUsernameEmail">Username</label>

                <input type="text" class="form-control" id="inputUsernameEmail" required="" name="username" >
                              </div>
              <div class="form-group">
                <!-- <a class="pull-right" href="#">Forgot password?</a> -->
                <label for="inputPassword" >Password</label>
                <input type="password" class="form-control" id="inputPassword"  name="password" required="">
                 </div>
              
              <button type="submit" class="btn btn btn-primary">
                Log In
              </button>
            </form>
            <br>
            <div>
                <span>
                    Become A Member? <a href="/register/">Sign up</a>
                </span>
            </div>
          
          </div>
          
        </div>
      </div>
    <!-- footer part start-->
    <footer class="footer-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-md-4 col-xl-3">
                    <div class="single-footer-widget footer_1">
                        <a href="index"> <img src="img/logo.png" alt=""> </a>
                        <p>But when shot real her. Chamber her one visite removal six
                            sending himself boys scot exquisite existend an </p>
                        <p>But when shot real her hamber her </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Newsletter</h4>
                        <p>Stay updated with our latest trends Seed heaven so said place winged over given forth fruit.
                        </p>
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Enter email address'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email address'">
                                    <div class="input-group-append">
                                        <button class="btn btn_1" type="button"><i class="ti-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="social_icon">
                            <a href="#"> <i class="ti-facebook"></i> </a>
                            <a href="#"> <i class="ti-twitter-alt"></i> </a>
                            <a href="#"> <i class="ti-instagram"></i> </a>
                            <a href="#"> <i class="ti-skype"></i> </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-md-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Contact us</h4>
                        <div class="contact_info">
                            <p><span> Address :</span> Hath of it fly signs bear be one blessed after </p>
                            <p><span> Phone :</span> +2 36 265 (8060)</p>
                            <p><span> Email : </span>info@colorlib.com </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright_part_text text-center">  
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer part end-->

    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>